{
    'name': 'HRMS Hide Fields',
    'version': '19.0.7.0.0',
    'summary': 'Hides specific fields from Employee form and list views',
    'author': 'Custom',
    'category': 'Human Resources',
    'depends': [
        'hr',
        'hr_salary_components',
        'hr_homeworking',
        'hr_org_chart',
        'hr_payroll_community',
        'hr_employee_updation',
        'employee_epf_esic_documents_final',
        'om_emp_dashboard',
        'ohrms_core',
    ],
    'data': [
        'views/01_hide_salary_tab_fields.xml',
        'views/02_hide_homeworking_fields.xml',
        'views/03_hide_org_chart.xml',
        'views/04_hide_payroll_fields.xml',
        'views/05_hide_updation_fields.xml',
        'views/07_hide_om_dashboard_fields.xml',
        'views/08_hide_base_employee_form_fields.xml',
        'views/09_hide_employee_list_view.xml',
        'views/10_hide_ohrms_list_view.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'LGPL-3',
}
